USE MASTER
GO

CREATE DATABASE BIBLIOTECA_CIBERTEC
GO

USE BIBLIOTECA_CIBERTEC
GO

CREATE TABLE ALUMNO(
	ID INT PRIMARY KEY IDENTITY,
	DNI char(8),
    NOMBRE VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONO VARCHAR(20)
)
GO

CREATE TABLE LIBRO(
    ID INT PRIMARY KEY IDENTITY,
    TITULO VARCHAR(200),
    AUTOR VARCHAR(100),
    CATEGORIA VARCHAR(50),
    ESTADO VARCHAR(20) -- 'Disponible' o 'rentado'
)
GO